maintainer       "Ian Thomas"
maintainer_email "ianedwardthomas@gmail.com"
license          "All rights reserved"
description      "Installs/Configures Chiminey"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends "build-essential"
depends "git"
depends "apt"
depends "iptables"
depends "postgresql"
depends "redis"
